### ISSUE TITLE
Questioin: What is the production cost ?

### ISSUE THREAD

**Issue by markbirss** [ddB0515/nRF52840-BBoard#2]
Hi @ddB0515, 

What is the actual production cost  ?

Have you been able to recently have some boards made ?

Have you tried connecting E-Paper or LoRa devices at all yet ?

Here is a DIY Meshtastic using nRF52840 Dongle PCA10059 dongle 3.71inch E-Paper and NiceRF SX1262 868 LoRa

But these and other nRF82540 based devices are missing WiFi

![20220322_034204](https://user-images.githubusercontent.com/22388007/160581955-07d2bd2e-7352-4a5b-8584-3a97877a0237.jpg)

**Comment by ddB0515** [comment]
Hello @markbirss 

I haven't calculated price for a board but can give some estimate based on current prices (keep in mind that are higher now then is were back when I was making this board)
E73-2G4M08S1C - 9$(from eByte Alibaba store- I think on larger quantity you get discount)
AP2112K-3.3 - 0.37$
LTC4054 - 2.52$ (but not needed if you don't have battery)
AO3407 - 0.41$
USB-C - 0.6$
Other(passive components & connectors) - 3-5$

So total estimate for one board is 15-18$ (depends where you sourcing components)
That is almost double the price I have paid back then (think less than 10$ was whole BOM)
But if you would go for more boards ( >10) that should be way less 

For LoRa or WiFi can be added extra chip but maybe then think about using ESP32 that have BT and WiFi in one
Also there is a lot of boards to choose from 

Hope this helped a bit

**Comment by markbirss** [comment]
@ddB0515 Ok, yes thank you tha helps

I understand the price increases and sourcing components sometimes make it difficult to actual have boards made...

Here some more info if you might be interested in Meshtastic below

Meshtastic currently supports both ESP32 and nRF82540, but your board looks interesting as it adds wifi to nRF82540
Meshtastic has a neat web interface 

The nRF82540 is just much more low power friendly than ESP32 (outdoor solar install)

Incidentally I did the Adafruit UF2 bootloader support for the MDBT50Q-DB-40
https://www.raytac.com/product/ins.php?index_id=81
https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/233

and added Meshtastic support for faster e-Papers on Meshtastic
https://github.com/meshtastic/Meshtastic-device/pull/1240

But im having odd issues drive the same e-Inks on the PCA10059 dongle, the partial screen updates are leaving lots of ghosting so I need to use full updates

The RAK6431 drivers 1.54, 2.9 and 4.2 inch with fast parital updates with no issues (but wont work with the 3.71 inch)
https://youtu.be/B_LEgEg2m9w
https://youtu.be/CKjeupzCYN8

For comparison here is a RAK nRF82540 based supported Meshtastic kit ($25)
https://store.rakwireless.com/collections/kits-bundles/products/wisblock-meshtastic-starter-kit
Adding OLED or e-Paper prices increases quickly

**Comment by ddB0515** [comment]
I think it would be easy to add [SX1262](https://www.semtech.com/products/wireless-rf/lora-core/sx1262) module to my board and have it tested
I don't have currently any SX1262 but can order one (as is 8$ piece[LINK](https://www.aliexpress.com/item/1005002876624258.html)) but bigger issue for me is to get that EPD 3.7"
Where did you order it? Can you send link pls
Also does it needs to be RAK modules? or you can work with any LoRa modules?

**Comment by markbirss** [comment]
Hi

No it does not have to be RAK modules, there are quite a few supported Meshtastic LoRa modules

ie RFM96 and SX126x variants, i not tried RFM96 with nRF82540

I have the E-Paper screens listed in the PR here would also work 1.54, .9 and 4.2 (actually more might work as the GxEPD2 library is used)

https://github.com/meshtastic/Meshtastic-device/pull/1240

200x200
1.54 inch e-paper display high resolution 200x200 partial refresh fast speed GDEW0154M09
https://www.buy-lcd.com/products/-381

296x128
2.9 inch e-paper display SPI Support for partial refresh 4 grayscale e-ink module screen GDEW029T5D
https://www.buy-lcd.com/products/-51

300x400
4.2 inch e-ink panel SPI interface 4 Grayscale buy e-paper display partial refresh GDEW042T2
https://www.buy-lcd.com/products/-85

Epaper HAT Connection Adapter Board for E Ink Display
https://www.buy-lcd.com/products/-27

**Comment by markbirss** [comment]
@ddB0515 

You will need a SPI SX1262 module
e.g
https://www.amazon.com/dp/B07K2WTLYY

**Comment by ddB0515** [comment]
Thanks for link but already ordered 2x [LoRa Module](https://www.aliexpress.com/item/1005003087292795.html)
It's same SPI one different manufacturer 

Also for your issue with partial update are you sure that EDP controller on that 3.7" supports partial update?
Also have you checked with other MCU(ESP32, STM32 or any other) just to be sure is not till controller on EDP

I can't test anything until get this and looks like that is not going to be until May/June :(

**Comment by markbirss** [comment]
Ok, meshtastic uses RadioLib for SPI LoRa Radio communication
https://github.com/jgromes/RadioLib

The 3.71 actually supports via GxEPD2 what is called "charge balancing waveform table for differential update" for that display
https://github.com/ZinggJM/GxEPD2/blob/master/MyEPDs_UpdateInfos.pdf

But the 2.9 and 4.2 (fast partial update) inch ones that i have added support for the RAK4361 nRF82540 board gives me the same bad ghosting effect also on my DIY PCA100059 but works perfectly in the youtube video links i sent earlier

It only the 1.54 inch that works with fast partial updates on my DIY board

So it might relate more to the chosen pin out i used as i already moved to a regulated 3.3v 500mA supply (too avoid possible bad too little current from USB supply)

Also oddly the 3.71 would not work on the RAK6431 board at all

The other LilyGo T-ECHO also only has a 1.54 inch (partial updates has not been enabled using old modified GxEPD2) library

The RAK14000 e-paper for which i also added support is not actually supported at all by GxEPD2 and partial updates dont work
https://github.com/meshtastic/Meshtastic-device/pull/1199

and has a line at the bottom as im using another e-ink support from GxEPD2

So lets keep in touch when you receive your parts

**Comment by markbirss** [comment]
@ddB0515 

Oh i even went as far to test 9.7inch Parallel ITE8951 HAT version on PCA10059

![20220310_184056](https://user-images.githubusercontent.com/22388007/160621665-564cdf6e-e5ec-4d07-8ad0-b54fb8e523c3.jpg)

**Comment by markbirss** [comment]
mark.birss@gmail.com

**Comment by markbirss** [comment]
@ddB0515 

I managed to find out why my e-paper picture gets ghosting, i had use the E-Paper RESET line, but it is not needed

**Comment by markbirss** [comment]
@ddB0515 

I have changed my LoRa Radio module to make use of the Waveshare SX1262 which adds TXEN and RXEN and is much more stable that the NiceRF868

https://www.waveshare.com/core1262-868m.htm
